#include <string.h>

const std::string ACH_50 = "BEGGINER COLLECTOR,COLLECT 50 TRASHES";
const std::string ACH_100 = "INTERMEDIATE COLLECTOR,COLLECT 100 TRASHES";
const std::string ACH_250 ="ADVANCED COLLECTOR,COLLECT 250 TRASHES";
const std::string ACH_500 ="PRO COLLECTOR,COLLECT 500 TRASHES";
const std::string ACH_1000 ="EXPERT COLLECTOR,COLLECT 1000 TRASHES";
const std::string ACH_2000= "MASTER COLLECTOR,COLLECT 2000 TRASHES";

const std::string ACH_10_SINGLE = "CORRECTNESS,COLLECT 10 TRASHES IN SINGLE RUN";
const std::string ACH_20_SINGLE = "FLAWLESSNESS,COLLECT 20 TRASHES IN SINGLE RUN";
const std::string ACH_50_SINGLE = "CAREFULLNESS,COLLECT 50 TRASHES IN SINGLE RUN";
const std::string ACH_100_SINGLE = "FAULTLESSNESS,COLLECT 100 TRASHES IN SINGLE RUN";
const std::string ACH_150_SINGLE = "ERRORLESS,COLLECT 150 TRASHES IN SINGLE RUN";
const std::string ACH_250_SINGLE = "PERFECTION,COLLECT 250 TRASHES IN SINGLE RUN";
