#include <string.h>

const std::string ACH_25 = "T1_BEGGINER COLLECTOR,GRAB 25 TRASHES IN ONE RUN";
const std::string ACH_50 = "T2_APPRENTICE,GRAB 50 TRASHES IN ONE RUN";
const std::string ACH_100 ="T3_ADVANCED COLLECTOR,GRAB 100 TRASHES IN ONE RUN";
const std::string ACH_175 ="T4_PRO COLLECTOR,GRAB 175 TRASHES IN ONE RUN";
const std::string ACH_300 ="T5_EXPERT COLLECTOR,GRAB 300 TRASHES IN ONE RUN";
const std::string ACH_500= "T6_MASTER COLLECTOR,GRAB 500 TRASHES IN ONE RUN";

const std::string ACH_10_SINGLE = "T7_CORRECTNESS,GRAB 10 TRASHES IN A ROW";
const std::string ACH_20_SINGLE = "T8_YOU SHALL NOT PASS,GRAB 20 TRASHES IN A ROW";
const std::string ACH_35_SINGLE = "T9_FIREWALL,GRAB 35 TRASHES IN A ROW";
const std::string ACH_50_SINGLE = "T10_FAULTLESSNESS,GRAB 50 TRASHES IN A ROW";
const std::string ACH_75_SINGLE = "T11_ERRORLESS,GRAB 75 TRASHES IN A ROW";
const std::string ACH_150_SINGLE = "T12_NINJA,GRAB 150 TRASHES IN A ROW";

const std::string ACH_HARDCORE = "T13_HARDCORE GAMER,PLAY 100 TIMES";
const std::string ACH_MASSIVE = "T14_MASSIVE COLLECTOR,COLLECT OVERALL\n 5000 TRASHES";
const std::string ACH_BLIND = "T15_ARE YOU BLIND?,MISS 10 TIMES IN A ROW";
const std::string ACH_AVOIDER  = "T16_BOMB AVOIDER, COLLECT 100 TRASHES \nWITHOUT DESTROYING ANY BOMBS";

