#include <string.h>

const std::string ACH_50 = "T1BEGGINER COLLECTOR,GRAB 50 TRASHES IN ONE RUN";
const std::string ACH_100 = "T2APPRENTICE,GRAB 100 TRASHES IN ONE RUN";
const std::string ACH_250 ="T3ADVANCED COLLECTOR,GRAB 250 TRASHES IN ONE RUN";
const std::string ACH_500 ="T4PRO COLLECTOR,GRAB 500 TRASHES IN ONE RUN";
const std::string ACH_1000 ="T5EXPERT COLLECTOR,GRAB 1000 TRASHES IN ONE RUN";
const std::string ACH_2000= "T6MASTER COLLECTOR,GRAB 2000 TRASHES IN ONE RUN";

const std::string ACH_10_SINGLE = "T7CORRECTNESS,GRAB 10 TRASHES IN A ROW";
const std::string ACH_20_SINGLE = "T8YOU SHALL NOT PASS,GRAB 20 TRASHES IN A ROW";
const std::string ACH_50_SINGLE = "T9FIREWALL,GRAB 50 TRASHES IN A ROW";
const std::string ACH_100_SINGLE = "T10FAULTLESSNESS,GRAB 100 TRASHES IN A ROW";
const std::string ACH_150_SINGLE = "T11ERRORLESS,GRAB 150 TRASHES IN A ROW";
const std::string ACH_250_SINGLE = "T12NINJA,GRAB 250 TRASHES IN A ROW";

const std::string ACH_HARDCORE = "T13HARDCORE GAMER,PLAY 100 TIMES";
const std::string ACH_MASSIVE = "T14MASSIVE COLLECTOR,COLLECT OVERALL\n 10000 TRASHES";
const std::string ACH_BLIND = "T15ARE YOU BLIND?,MISS 10 TIMES IN A ROW";

